# Site settings
title: Francisco Jara
email: fcojara506@gmail.com
description: website
url: "localhost:4000" 
github_username:  fcojara506

# Build settings
include:
  - _pages



# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false